create table if not exists public.web_vitals_events (
  id bigint generated by default as identity primary key,
  source text not null default 'barberflow-web',
  user_agent text not null default 'unknown',
  sent_at timestamptz not null default now(),
  metric_name text not null check (metric_name in ('LCP', 'INP', 'CLS')),
  metric_value double precision not null,
  metric_rating text not null check (metric_rating in ('good', 'needs-improvement', 'poor')),
  metric_timestamp timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists web_vitals_events_created_at_idx
  on public.web_vitals_events (created_at desc);

create index if not exists web_vitals_events_metric_name_idx
  on public.web_vitals_events (metric_name);

alter table public.web_vitals_events enable row level security;

drop policy if exists "service_role_full_access_web_vitals" on public.web_vitals_events;
create policy "service_role_full_access_web_vitals"
  on public.web_vitals_events
  for all
  to service_role
  using (true)
  with check (true);

